name: ChehabEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - gcc_impl_linux-64=14.2.0
  - gcc_linux-64=14.2.0
  - gxx_impl_linux-64=14.2.0
  - gxx_linux-64=14.2.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libsanitizer=14.2.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - nano=8.3
  - ncurses=6.5
  - openssl=3.5.0
  - pip=24.2
  - python=3.12.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.5.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - ale-py==0.10.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - bert-score==0.3.13
      - bitsandbytes==0.45.5
      - certifi==2024.12.14
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.0
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.4.1
      - dill==0.3.8
      - distlib==0.3.9
      - distro==1.9.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - evaluate==0.4.3
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - flatbuffers==24.12.23
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - identify==2.6.9
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.9.0
      - joblib==1.4.2
      - keras==3.8.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lxml==5.3.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - namex==0.0.8
      - networkx==3.4.2
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.68.2
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optimum==1.24.0
      - optree==0.13.1
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.3.7
      - portalocker==3.1.1
      - pre-commit==4.2.0
      - propcache==0.3.0
      - protobuf==5.29.2
      - psutil==6.1.1
      - pyarrow==19.0.1
      - pycryptodome==3.21.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygame==2.6.1
      - pygments==2.19.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rouge-score==0.1.2
      - sacrebleu==2.5.1
      - safetensors==0.5.2
      - sb3-contrib==2.4.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - sentence-transformers==3.4.1
      - shimmy==2.0.0
      - six==1.16.0
      - sniffio==1.3.1
      - stable-baselines3==2.4.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==2.5.0
      - tf-keras==2.19.0
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - torch==2.5.1
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torchviz==0.0.3
      - tqdm==4.67.1
      - transformers==4.48.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - vec2text==0.0.13
      - virtualenv==20.29.3
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - xxhash==3.5.0
      - yarl==1.18.3

